[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "grantha_converter"
version = "0.0.1"
authors = [
  { name="Your Name", email="you@example.com" },
]
description = "A tool to convert Grantha data"
readme = "tools/lib/grantha_converter/README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.setuptools.packages.find]
where = ["tools/lib"]

[project.urls]
"Homepage" = "https://github.com/pypa/sampleproject"
"Bug Tracker" = "https://github.com/pypa/sampleproject/issues"

[project.scripts]
grantha-converter = "grantha_converter.cli:main"
vishvas-markup-to-structured-markdown = "grantha_converter.html_details_cli:main"
grantha-repair-devanagari = "grantha_converter.devanagari_repair_cli:main"
