# In pyproject.toml

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "grantha_converter"
version = "0.0.1"
# ... (rest of your project section is fine) ...
description = "A tool to convert Grantha data"
readme = "tools/lib/grantha_converter/README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.setuptools]
packages = ["find:"]

[project.urls]
"Homepage" = "https://github.com/pypa/sampleproject"
"Bug Tracker" = "https://github.com/pypa/sampleproject/issues"

[project.scripts]
grantha-converter = "tools.lib.grantha_converter.cli:main"
vishvas-markup-to-structured-markdown = "tools.lib.grantha_converter.html_details_cli:main"
grantha-repair-devanagari = "tools.lib.grantha_converter.devanagari_repair_cli:main"
pdf-ocr = "tools.scripts.pdf_ocr:main"